Repository cmput301-w25/project-impostersyndrome, pull requests merged in 2025-03, with the labels that each got.

#129 Feature/04.01.01 fix merge
  code/app/src/main/AndroidManifest.xml
  code/app/src/main/java/com/example/impostersyndrom/AddMoodActivity.java
  code/app/src/main/java/com/example/impostersyndrom/EmojiSelectionActivity.java
  code/app/src/main/java/com/example/impostersyndrom/MainActivity.java
  code/app/src/main/java/com/example/impostersyndrom/Mood.java
  code/app/src/main/java/com/example/impostersyndrom/MoodAdapter.java
  code/app/src/main/java/com/example/impostersyndrom/ViewMoodActivity.java
  code/app/src/main/res/drawable/emoji_angry.png
  code/app/src/main/res/drawable/emoji_confused.png
  code/app/src/main/res/drawable/emoji_disgust.png
  code/app/src/main/res/drawable/emoji_fear.png
  code/app/src/main/res/drawable/emoji_happy.png
  code/app/src/main/res/drawable/emoji_sad.png
  code/app/src/main/res/drawable/emoji_shame.png
  code/app/src/main/res/drawable/emoji_surprised.png
  code/app/src/main/res/layout/activity_add_mood.xml
  code/app/src/main/res/layout/activity_emoji_selection.xml
  code/app/src/main/res/layout/activity_main.xml
  code/app/src/main/res/layout/activity_view_mood.xml
  code/app/src/main/res/layout/item_mood.xml
Labels: enhancement, High Priority

#116 Fixed scroll
  code/app/src/main/res/layout/activity_add_mood.xml
Labels: bug, Medium Priority

#135 implemented 3 word features, added updating character + word count, c…
  code/app/src/main/java/com/example/impostersyndrom/AddMoodActivity.java
  code/app/src/main/java/com/example/impostersyndrom/EmojiSelectionActivity.java
  code/app/src/main/java/com/example/impostersyndrom/Mood.java
  code/app/src/main/res/drawable/left_arrow.png
  code/app/src/main/res/drawable/white_checkmark.png
  code/app/src/main/res/layout/activity_add_mood.xml
  code/app/src/main/res/layout/activity_emoji_selection.xml
Labels: High Priority

#137 Feature/01.04.01
  code/app/build.gradle.kts
  code/app/src/main/AndroidManifest.xml
  code/app/src/main/java/com/example/impostersyndrom/MainActivity.java
  code/app/src/main/java/com/example/impostersyndrom/MoodDetailActivity.java
  code/app/src/main/res/layout/activity_mood_detail.xml
  code/build.gradle.kts
Labels: High Priority

#136 changed gallery ui, subject to change
  code/app/src/main/java/com/example/impostersyndrom/AddMoodActivity.java
  code/app/src/main/java/com/example/impostersyndrom/ImageHandler.java
  code/app/src/main/res/drawable/ic_camera.png
  code/app/src/main/res/layout/activity_add_mood.xml
  code/app/src/main/res/values/strings.xml
Labels: High Priority

#169 following management
  code/app/build.gradle.kts
  code/app/src/main/AndroidManifest.xml
  code/app/src/main/java/com/example/impostersyndrom/controller/FollowingAdapter.java
  code/app/src/main/java/com/example/impostersyndrom/controller/PendingRequestsAdapter.java
  code/app/src/main/java/com/example/impostersyndrom/controller/UserListAdapter.java
  code/app/src/main/java/com/example/impostersyndrom/controller/ViewPagerAdapter.java
  code/app/src/main/java/com/example/impostersyndrom/model/FollowRequest.java
  code/app/src/main/java/com/example/impostersyndrom/view/FollowingActivity.java
  code/app/src/main/java/com/example/impostersyndrom/view/FollowingFragment.java
  code/app/src/main/java/com/example/impostersyndrom/view/MainActivity.java
  code/app/src/main/java/com/example/impostersyndrom/view/PendingRequestsFragment.java
  code/app/src/main/java/com/example/impostersyndrom/view/SearchActivity.java
  code/app/src/main/res/drawable/button_follow.xml
  code/app/src/main/res/drawable/button_unfollow.xml
  code/app/src/main/res/drawable/clear.png
  code/app/src/main/res/drawable/follower.png
  code/app/src/main/res/drawable/list_item_bg.xml
  code/app/src/main/res/drawable/nopfp.png
  code/app/src/main/res/drawable/search_bar_bg.xml
  code/app/src/main/res/layout/activity_following.xml
  code/app/src/main/res/layout/activity_search.xml
  code/app/src/main/res/layout/fragment_list.xml
  code/app/src/main/res/layout/item_following.xml
  code/app/src/main/res/layout/item_pending_request.xml
  code/app/src/main/res/layout/user_list_item.xml
  code/app/src/main/res/values/styles.xml
Labels: 13 Story Points

#177 Feature/05.03.01
  code/app/src/main/java/com/example/impostersyndrom/controller/MoodAdapter.java
  code/app/src/main/java/com/example/impostersyndrom/model/MoodItem.java
  code/app/src/main/java/com/example/impostersyndrom/view/MainActivity.java
  code/app/src/main/java/com/example/impostersyndrom/view/MoodDetailActivity.java
  code/app/src/main/res/layout/activity_main.xml
  code/app/src/main/res/layout/item_mood.xml
Labels: 5 Story Points, High Priority

#171 Feature/us 03.03.01
  code/app/build.gradle.kts
  code/app/src/main/AndroidManifest.xml
  code/app/src/main/java/com/example/impostersyndrom/controller/FollowingAdapter.java
  code/app/src/main/java/com/example/impostersyndrom/controller/PendingRequestsAdapter.java
  code/app/src/main/java/com/example/impostersyndrom/controller/UserListAdapter.java
  code/app/src/main/java/com/example/impostersyndrom/model/ProfileDataManager.java
  code/app/src/main/java/com/example/impostersyndrom/view/EditProfileActivity.java
  code/app/src/main/java/com/example/impostersyndrom/view/FollowingActivity.java
  code/app/src/main/java/com/example/impostersyndrom/view/FollowingFragment.java
  code/app/src/main/java/com/example/impostersyndrom/view/MainActivity.java
  code/app/src/main/java/com/example/impostersyndrom/view/PendingRequestsFragment.java
  code/app/src/main/java/com/example/impostersyndrom/view/ProfileActivity.java
  code/app/src/main/java/com/example/impostersyndrom/view/SearchActivity.java
  code/app/src/main/java/com/example/impostersyndrom/view/UserProfileActivity.java
  code/app/src/main/res/drawable/circle.xml
  code/app/src/main/res/drawable/default_person.png
  code/app/src/main/res/drawable/ic_edit.png
  code/app/src/main/res/drawable/ic_logout.png
  code/app/src/main/res/drawable/nopfp.png
  code/app/src/main/res/layout/activity_edit_profile.xml
  code/app/src/main/res/layout/activity_main.xml
  code/app/src/main/res/layout/bottom_sheet_image_picker.xml
  code/app/src/main/res/layout/item_following.xml
  code/app/src/main/res/layout/item_pending_request.xml
  code/app/src/main/res/layout/nav_header.xml
  code/app/src/main/res/layout/navigation_layout.xml
  code/app/src/main/res/layout/profile_activity.xml
  code/app/src/main/res/layout/user_list_item.xml
  code/app/src/main/res/layout/user_profile_activity.xml
  code/app/src/main/res/menu/nav_menu.xml
  code/gradle/libs.versions.toml
Labels: High Priority

#178 public moods
  code/app/src/main/java/com/example/impostersyndrom/view/MainActivity.java
Labels: 2 Story Points

#195 Finished filter mood by reason
  code/app/src/main/java/com/example/impostersyndrom/model/MoodFilter.java
  code/app/src/main/java/com/example/impostersyndrom/view/FollowingMoodsFragment.java
  code/app/src/main/java/com/example/impostersyndrom/view/MainActivity.java
  code/app/src/main/java/com/example/impostersyndrom/view/MyMoodsFragment.java
  code/app/src/main/res/drawable/filter_reason_background.xml
  code/app/src/main/res/layout/filter_mood_dialog.xml
Labels: 5 Story Points

#200 Wow/spotify rec
  README.md
  code/app/build.gradle.kts
  code/app/src/main/AndroidManifest.xml
  code/app/src/main/java/com/example/impostersyndrom/network/SpotifyApiService.java
  code/app/src/main/java/com/example/impostersyndrom/network/SpotifyAuthClient.java
  code/app/src/main/java/com/example/impostersyndrom/network/SpotifyAuthService.java
  code/app/src/main/java/com/example/impostersyndrom/network/SpotifyRecommendationResponse.java
  code/app/src/main/java/com/example/impostersyndrom/spotify/MoodAudioMapper.java
  code/app/src/main/java/com/example/impostersyndrom/spotify/SpotifyAuthResponse.java
  code/app/src/main/java/com/example/impostersyndrom/spotify/SpotifyManager.java
  code/app/src/main/java/com/example/impostersyndrom/view/MainActivity.java
  code/app/src/main/java/com/example/impostersyndrom/view/MoodCardAdapter.java
  code/app/src/main/java/com/example/impostersyndrom/view/MoodDetailActivity.java
  code/app/src/main/res/drawable/ic_music_note.xml
  code/app/src/main/res/drawable/ic_play_circle.xml
  code/app/src/main/res/layout/activity_mood_detail.xml
  code/app/src/main/res/layout/item_mood_card.xml
  code/app/src/main/res/layout/item_song_recommendation_card.xml
Labels: High Priority, WOW!

#198 updated pvt moods visibility
  code/app/src/main/java/com/example/impostersyndrom/view/FollowingMoodsFragment.java
Labels: High Priority

#202 Wow/profile recent moods
  code/app/src/main/java/com/example/impostersyndrom/model/EmojiUtils.java
  code/app/src/main/java/com/example/impostersyndrom/view/ProfileActivity.java
  code/app/src/main/java/com/example/impostersyndrom/view/UserProfileActivity.java
  code/app/src/main/res/layout/profile_activity.xml
  code/app/src/main/res/layout/user_profile_activity.xml
Labels: enhancement, WOW!

#217 Comments
  code/app/src/main/AndroidManifest.xml
  code/app/src/main/java/com/example/impostersyndrom/controller/CommentsAdapter.java
  code/app/src/main/java/com/example/impostersyndrom/model/Comment.java
  code/app/src/main/java/com/example/impostersyndrom/model/CommentDataManager.java
  code/app/src/main/java/com/example/impostersyndrom/view/CommentActivity.java
  code/app/src/main/java/com/example/impostersyndrom/view/MainActivity.java
  code/app/src/main/java/com/example/impostersyndrom/view/MoodDetailActivity.java
  code/app/src/main/res/drawable/comment_field_bg.xml
  code/app/src/main/res/drawable/remove.png
  code/app/src/main/res/drawable/reply.png
  code/app/src/main/res/drawable/send.png
  code/app/src/main/res/layout/activity_mood_detail.xml
  code/app/src/main/res/layout/item_comment.xml
Labels: 8 Story Points
