Repository cmput301-w25/project-impostersyndrome, pull requests merged in 2025-02, with the labels that each got.

#113 Feature/US 03.01.01
  code/app/build.gradle.kts
  code/app/src/main/AndroidManifest.xml
  code/app/src/main/java/com/example/impostersyndrom/ForgotPasswordActivity.java
  code/app/src/main/java/com/example/impostersyndrom/LoginActivity.java
  code/app/src/main/java/com/example/impostersyndrom/MainActivity.java
  code/app/src/main/java/com/example/impostersyndrom/RegisterActivity.java
  code/app/src/main/res/layout/activity_forgot_password.xml
  code/app/src/main/res/layout/activity_login.xml
  code/app/src/main/res/layout/activity_main.xml
  code/app/src/main/res/layout/activity_register.xml
  code/gradle/libs.versions.toml
Labels: High Priority

#114 Feature/US 02.02.01 , 02.03.01
  README.md
  code/app/build.gradle.kts
  code/app/src/main/AndroidManifest.xml
  code/app/src/main/java/com/example/impostersyndrom/AddMoodActivity.java
  code/app/src/main/java/com/example/impostersyndrom/EmojiSelectionActivity.java
  code/app/src/main/java/com/example/impostersyndrom/ImageHandler.java
  code/app/src/main/java/com/example/impostersyndrom/LoginActivity.java
  code/app/src/main/java/com/example/impostersyndrom/MainActivity.java
  code/app/src/main/java/com/example/impostersyndrom/Mood.java
  code/app/src/main/java/com/example/impostersyndrom/User.java
  code/app/src/main/res/layout/activity_add_mood.xml
  code/app/src/main/res/xml/file_paths.xml
  code/gradle/libs.versions.toml
Labels: High Priority

#115 finished US 2.04.01
  code/app/src/main/java/com/example/impostersyndrom/AddMoodActivity.java
  code/app/src/main/java/com/example/impostersyndrom/Mood.java
  code/app/src/main/res/drawable/person.png
  code/app/src/main/res/layout/activity_add_mood.xml
  code/app/src/main/res/menu/group_menu.xml
Labels: High Priority

#110 Update README.md
  README.md
Labels: Low Priority

#117 fix dev branch
  code/app/src/main/java/com/example/impostersyndrom/Mood.java
  code/app/src/main/res/layout/activity_add_mood.xml
Labels: High Priority

#124 Emoji UI fixes
  code/app/src/main/java/com/example/impostersyndrom/AddMoodActivity.java
  code/app/src/main/java/com/example/impostersyndrom/EmojiSelectionActivity.java
  code/app/src/main/java/com/example/impostersyndrom/Mood.java
  code/app/src/main/res/drawable/emoji_angry.png
  code/app/src/main/res/drawable/emoji_confused.png
  code/app/src/main/res/drawable/emoji_disgust.png
  code/app/src/main/res/drawable/emoji_fear.png
  code/app/src/main/res/drawable/emoji_happy.png
  code/app/src/main/res/drawable/emoji_sad.png
  code/app/src/main/res/drawable/emoji_shame.png
  code/app/src/main/res/drawable/emoji_surprised.png
  code/app/src/main/res/layout/activity_add_mood.xml
  code/app/src/main/res/layout/activity_emoji_selection.xml
Labels: bug, High Priority

#123 fixed locatoin of person icon
  code/app/src/main/res/layout/activity_add_mood.xml
Labels: bug, Medium Priority
